version: "3.8"

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8090:8090"
    environment:
      - API_KEY=1c951a7f
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_BACKEND_URL=http://backend:8090
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
